id: I41D1A89A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:04:54+00:00'
last_modified: '2022-06-08T05:46:26.490720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21295
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （སྡེ་དགེ་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4D9A:
      image_group_id: I2432
      title: ''
      total_pages: 608
      order: 1
      base_file: 4D9A.txt
    '2861':
      image_group_id: I2433
      title: ''
      total_pages: 668
      order: 2
      base_file: 2861.txt
    3FB6:
      image_group_id: I2434
      title: ''
      total_pages: 566
      order: 3
      base_file: 3FB6.txt
    F48A:
      image_group_id: I2435
      title: ''
      total_pages: 548
      order: 4
      base_file: F48A.txt
    '9436':
      image_group_id: I2436
      title: ''
      total_pages: 732
      order: 5
      base_file: 9436.txt
    4EE8:
      image_group_id: I2437
      title: ''
      total_pages: 722
      order: 6
      base_file: 4EE8.txt
    769F:
      image_group_id: I2438
      title: ''
      total_pages: 816
      order: 7
      base_file: 769F.txt
    0D81:
      image_group_id: I2439
      title: ''
      total_pages: 738
      order: 8
      base_file: 0D81.txt
    2EAE:
      image_group_id: I2440
      title: ''
      total_pages: 664
      order: 9
      base_file: 2EAE.txt
    '1213':
      image_group_id: I2441
      title: ''
      total_pages: 756
      order: 10
      base_file: 1213.txt
    6A1A:
      image_group_id: I2442
      title: ''
      total_pages: 693
      order: 11
      base_file: 6A1A.txt
    44A9:
      image_group_id: I2443
      title: ''
      total_pages: 566
      order: 12
      base_file: 44A9.txt
    B24F:
      image_group_id: I2444
      title: ''
      total_pages: 626
      order: 13
      base_file: B24F.txt
    B407:
      image_group_id: I2445
      title: ''
      total_pages: 630
      order: 14
      base_file: B407.txt
    0393:
      image_group_id: I2446
      title: ''
      total_pages: 636
      order: 15
      base_file: 0393.txt
    4D26:
      image_group_id: I2447
      title: ''
      total_pages: 686
      order: 16
      base_file: 4D26.txt
    D8E7:
      image_group_id: I2448
      title: ''
      total_pages: 726
      order: 17
      base_file: D8E7.txt
    '6375':
      image_group_id: I2449
      title: ''
      total_pages: 626
      order: 18
      base_file: 6375.txt
    '7288':
      image_group_id: I2450
      title: ''
      total_pages: 636
      order: 19
      base_file: 7288.txt
    78E1:
      image_group_id: I2451
      title: ''
      total_pages: 784
      order: 20
      base_file: 78E1.txt
    53A4:
      image_group_id: I2452
      title: ''
      total_pages: 772
      order: 21
      base_file: 53A4.txt
    107E:
      image_group_id: I2453
      title: ''
      total_pages: 680
      order: 22
      base_file: 107E.txt
    B4C7:
      image_group_id: I2454
      title: ''
      total_pages: 674
      order: 23
      base_file: B4C7.txt
    17DA:
      image_group_id: I2455
      title: ''
      total_pages: 610
      order: 24
      base_file: 17DA.txt
    64B5:
      image_group_id: I2456
      title: ''
      total_pages: 606
      order: 25
      base_file: 64B5.txt
    '6465':
      image_group_id: I2457
      title: ''
      total_pages: 640
      order: 26
      base_file: 6465.txt
    ABA3:
      image_group_id: I2458
      title: ''
      total_pages: 654
      order: 27
      base_file: ABA3.txt
    FCBF:
      image_group_id: I2459
      title: ''
      total_pages: 636
      order: 28
      base_file: FCBF.txt
    8AB0:
      image_group_id: I2460
      title: ''
      total_pages: 628
      order: 29
      base_file: 8AB0.txt
    73B0:
      image_group_id: I2461
      title: ''
      total_pages: 646
      order: 30
      base_file: 73B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
