id: P006632
initial_creation_type: ocr
source_metadata:
  id: bdr:W21295
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （སྡེ་དགེ་པར་མ།）
  author: ''
  volumes:
    5e2f718859cd4e018263746d48bb8178:
      image_group_id: I2432
      title: ''
      volume_number: 1
      total_pages: 608
      base_file: v001.txt
    b010a42959384210a27fc2c096f6634f:
      image_group_id: I2433
      title: ''
      volume_number: 2
      total_pages: 668
      base_file: v002.txt
    3c3df209063f401fb43fdb7356815184:
      image_group_id: I2434
      title: ''
      volume_number: 3
      total_pages: 566
      base_file: v003.txt
    c6413da37a824dc1bb2f1e038224933a:
      image_group_id: I2435
      title: ''
      volume_number: 4
      total_pages: 548
      base_file: v004.txt
    3d65c2e1eca5480d80108a32a3cea6db:
      image_group_id: I2436
      title: ''
      volume_number: 5
      total_pages: 732
      base_file: v005.txt
    b69f6a545dcc4c6ca436f8e32e6b9095:
      image_group_id: I2437
      title: ''
      volume_number: 6
      total_pages: 722
      base_file: v006.txt
    3c8e92045eb342698aec8648d83ab34a:
      image_group_id: I2438
      title: ''
      volume_number: 7
      total_pages: 816
      base_file: v007.txt
    d57e0788e51149be93b98731eb1095c2:
      image_group_id: I2439
      title: ''
      volume_number: 8
      total_pages: 738
      base_file: v008.txt
    e0b7cdfa1dba430992e0b81331cb2521:
      image_group_id: I2440
      title: ''
      volume_number: 9
      total_pages: 664
      base_file: v009.txt
    e04d08de27eb42abab9ecbea83f27ea6:
      image_group_id: I2441
      title: ''
      volume_number: 10
      total_pages: 756
      base_file: v010.txt
    f69fc58606be4991b66ed517ef2d7aff:
      image_group_id: I2442
      title: ''
      volume_number: 11
      total_pages: 693
      base_file: v011.txt
    7971a45604154507b311b62d21666667:
      image_group_id: I2443
      title: ''
      volume_number: 12
      total_pages: 566
      base_file: v012.txt
    d6d171e76b1649fcbaf7bee25f916b3a:
      image_group_id: I2444
      title: ''
      volume_number: 13
      total_pages: 626
      base_file: v013.txt
    adff451fde0a4d78bcef6b8a4a833e7c:
      image_group_id: I2445
      title: ''
      volume_number: 14
      total_pages: 630
      base_file: v014.txt
    ee0c5652837a43abb9bb5af32703520b:
      image_group_id: I2446
      title: ''
      volume_number: 15
      total_pages: 636
      base_file: v015.txt
    731ca1eb97be4c489495015291b91ba3:
      image_group_id: I2447
      title: ''
      volume_number: 16
      total_pages: 686
      base_file: v016.txt
    890263b9a79e4395a32a3ca8003a9281:
      image_group_id: I2448
      title: ''
      volume_number: 17
      total_pages: 726
      base_file: v017.txt
    87a9d1ff66344f34a9362a5be28d1a97:
      image_group_id: I2449
      title: ''
      volume_number: 18
      total_pages: 626
      base_file: v018.txt
    b3cca19c24c646ed8bc7b9dc3c9e2390:
      image_group_id: I2450
      title: ''
      volume_number: 19
      total_pages: 636
      base_file: v019.txt
    57124d03ef434b2b98b90b80f50d630e:
      image_group_id: I2451
      title: ''
      volume_number: 20
      total_pages: 784
      base_file: v020.txt
    108123e96571491cadc8a6bb540b0323:
      image_group_id: I2452
      title: ''
      volume_number: 21
      total_pages: 772
      base_file: v021.txt
    7e41a35895c74431ae09ceb9b0e24c7c:
      image_group_id: I2453
      title: ''
      volume_number: 22
      total_pages: 680
      base_file: v022.txt
    16281332f6804dc893a725e2fbe7ae13:
      image_group_id: I2454
      title: ''
      volume_number: 23
      total_pages: 674
      base_file: v023.txt
    07e18fe6a53a4ee9817279898968541f:
      image_group_id: I2455
      title: ''
      volume_number: 24
      total_pages: 610
      base_file: v024.txt
    24c6a74ad77643d18d49c7bbc62cac0e:
      image_group_id: I2456
      title: ''
      volume_number: 25
      total_pages: 606
      base_file: v025.txt
    466a8b7725cc4576afb38a995498c867:
      image_group_id: I2457
      title: ''
      volume_number: 26
      total_pages: 640
      base_file: v026.txt
    b248bfd0f5ef40eba5db0a56896b0c25:
      image_group_id: I2458
      title: ''
      volume_number: 27
      total_pages: 654
      base_file: v027.txt
    44af45807c364b53b27dfd93f66bf827:
      image_group_id: I2459
      title: ''
      volume_number: 28
      total_pages: 636
      base_file: v028.txt
    54544dad80f141aab714dbb3b1bb4199:
      image_group_id: I2460
      title: ''
      volume_number: 29
      total_pages: 628
      base_file: v029.txt
    ee3f843695d2440f845a58636fc5eceb:
      image_group_id: I2461
      title: ''
      volume_number: 30
      total_pages: 646
      base_file: v030.txt
